### ISSUE TITLE
Will not calibrate on Pebble 2+HR

### ISSUE THREAD

**Issue by DewrDev** [kennedn/find-o-matic#2]
App will fail to get past the Calibration stage and will always sit showing the 'move wrist to calibrate compass' text. The Distance is correctly shown breifly after previewing the destination.

I tested this with my original classic Pebble connected to the same phone and after flipping the watch a couple of times, it got past the calibration stage and seemed to point me in the right direction.

**Comment by kennedn** [comment]
Hiya,

Apologies, I meant to remove the diorite platform from the supported list during the hackathon but it seems to have slipped my mind. The Pebble 2 is the only watch that did not ship with a compass module, so it sadly cannot be used with find-o-matic.

I will push a new version shortly that removes diorite from the supported list.

Cheers,
